require("dotenv").config();
import mongoose from "mongoose"; // or const mongoose = require('mongoose');

// TO CREATE A DATABASE AND CONNECT TO IT
// 1. Login to MOngoDB Atlas and create a free CLUSTER or choose an existing free cluster.
// 2. Specify the connection URI to the MongoDB Atlas free cluster. The connection URI can be obtained
//    by clicking the "connect" button on the free cluster and then clicking "Driver" and then copy
//    the link. The link is then pasted in the ".env" file and edited to insert the password.To
//    edit the password, just clear the <db_password> and replace with your admin password which
//    is generated by going to: "Security -> Database Access"
//    Also go to: "Security -> Network Access" and add IP Address "0.0.0.0/0" to allow connection from
//    any IP address all over the world.
// 3. Specify the "name" of the database to be created in the free cluster in the ".env" file, then
//    write the "connection" code and the "schema-model" to  create the database and its collection
//    (i.e. similar to table in sql)

let isConnected = false;

//create connection to the online database
const connectToDB = async() => {
    mongoose.set("strictQuery", true); // This must be set to prevent warning

    if (mongoose.connections[0].readyState || isConnected) {
        console.log("Already connected to MongoDB.");
        return;
    }

    // The actual connection to the online database occurs here
    try {
        await mongoose.connect(process.env.MONGODB_URI, {
            dbName: process.env.DB_NAME,
            useNewUrlParser: true,
            useUnifiedTopology: true,
        });

        isConnected = true;
        console.log("MongoDB connected successfully");
    } catch (error) {
        console.error("Error connecting to MongoDB: ", error);
        throw error;
    }
};

export default connectToDB;